output "infra_id" {
  description = "Cluster infraID (matches install/metadata.json)"
  value       = local.infra_id
}

output "api_vip" {
  description = "Virtual IP serving the cluster API, held by keepalived on a control-plane node"
  value       = var.api_vip
}

output "ingress_vip" {
  description = "Virtual IP serving *.apps, held by keepalived on a node running a router pod"
  value       = var.ingress_vip
}

output "node_mac_addresses" {
  description = "MACs Terraform pinned on each VM. Create DHCP reservations for these so control-plane addresses survive a rebuild."
  value = merge(
    local.single_node ? {} : { "${local.infra_id}-bootstrap" = local.bootstrap_mac },
    { for i, m in local.master_macs : "${local.infra_id}-master-${i}" => m },
    { for i, m in local.worker_macs : "${local.infra_id}-worker-${i}" => m },
  )
}

output "node_placement" {
  description = "Which Proxmox node each VM lands on. Masters are spread round-robin so one hypervisor failure cannot take the whole control plane."
  value = merge(
    local.single_node ? {} : { "${local.infra_id}-bootstrap" = local.bootstrap_node },
    { for i, n in local.master_nodes : "${local.infra_id}-master-${i}" => n },
    { for i, n in local.worker_nodes : "${local.infra_id}-worker-${i}" => n },
  )
}

output "api_url" {
  description = "Cluster API URL"
  value       = "https://api.${local.cluster_domain}:6443"
}

output "console_url" {
  description = "OpenShift web console URL"
  value       = "https://console-openshift-console.apps.${local.cluster_domain}"
}

output "kubeconfig_path" {
  description = "Path to the kubeconfig generated by openshift-install"
  value       = "${path.module}/../install/auth/kubeconfig"
}

output "kubeadmin_password_path" {
  description = "Path to the kubeadmin password generated by openshift-install"
  value       = "${path.module}/../install/auth/kubeadmin-password"
}

output "next_steps" {
  description = "What to do after terraform apply succeeds"
  value       = <<-EOT
    DNS records and cert-manager are managed by Terraform. The API and ingress
    VIPs are held by keepalived static pods on the cluster nodes, so nothing
    outside the cluster needs configuring.

    Before the first bringup, make sure DHCP reservations exist for the MACs in
    the `node_mac_addresses` output — the HAProxy backend list is generated
    from stable control-plane addresses.

    1. (First bringup) Watch bootstrap completion (~30-40 min):
         ./.bin/openshift-install --dir=install wait-for bootstrap-complete --log-level=info
    2. Destroy the bootstrap VM once the control plane is up:
         terraform destroy -target=proxmox_virtual_environment_vm.bootstrap
    3. Watch install completion (~30 min more):
         ./.bin/openshift-install --dir=install wait-for install-complete --log-level=info
    4. Use the cluster:
         export KUBECONFIG=$PWD/install/auth/kubeconfig
         oc get nodes
         oc whoami --show-console
         cat install/auth/kubeadmin-password

    For destroy/recreate, always go through scripts/04-bringup.sh — it
    regenerates ignitions when terraform state is empty (otherwise the 24h MCS
    bootstrap token in master.ign expires).
  EOT
}
