output "infra_id" {
  description = "Cluster infraID (matches install/metadata.json)"
  value       = local.infra_id
}

output "resource_group" {
  value = azurerm_resource_group.main.name
}

output "ignition_storage_account" {
  description = "Storage account hosting the bootstrap ignition blob"
  value       = azurerm_storage_account.cluster.name
}

output "api_lb_public_ip" {
  description = "Public IP of the external API LB"
  value       = azurerm_public_ip.api.ip_address
}

output "router_lb_public_ip" {
  description = "Public IP of the router LB"
  value       = azurerm_public_ip.router.ip_address
}

output "api_url" {
  description = "Cluster API URL"
  value       = "https://api.${local.cluster_name}.${var.base_domain}:6443"
}

output "console_url" {
  description = "OpenShift web console URL"
  value       = "https://console-openshift-console.apps.${local.cluster_name}.${var.base_domain}"
}

output "kubeconfig_path" {
  description = "Path to the kubeconfig generated by openshift-install"
  value       = "${path.module}/../install/auth/kubeconfig"
}

output "kubeadmin_password_path" {
  description = "Path to the kubeadmin password generated by openshift-install"
  value       = "${path.module}/../install/auth/kubeadmin-password"
}

output "next_steps" {
  description = "What to do after terraform apply succeeds"
  value       = <<-EOT
    DNS records, cert-manager, and the IngressController switch are all managed
    by Terraform — no manual cluster config required.

    1. (First bringup) Watch bootstrap completion (~30-40 min):
         ./.bin/openshift-install --dir=install wait-for bootstrap-complete --log-level=info
    2. Destroy the bootstrap VM (optional once cluster is healthy):
         terraform destroy \
           -target=azurerm_linux_virtual_machine.bootstrap \
           -target=azurerm_network_interface_backend_address_pool_association.bootstrap_external \
           -target=azurerm_network_interface_backend_address_pool_association.bootstrap_internal \
           -target=azurerm_network_interface.bootstrap \
           -target=azurerm_storage_blob.bootstrap_ignition
    3. Watch install completion (~30 min more):
         ./.bin/openshift-install --dir=install wait-for install-complete --log-level=info
    4. Use the cluster:
         export KUBECONFIG=$PWD/install/auth/kubeconfig
         oc get nodes
         oc whoami --show-console
         cat install/auth/kubeadmin-password

    For destroy/recreate, always go through scripts/04-bringup.sh — it
    regenerates ignitions when terraform state is empty (otherwise the 24h MCS
    bootstrap token in master.ign expires).
  EOT
}
